### ISSUE TITLE
Can't apply patches to Asterisk 13.7.0 

### ISSUE THREAD

**Issue by kosfango** [traud/asterisk-amr#5]
Hi guys,

Some patches can't applied to **Asterisk 13.7**:

[http://pastebin.com/wvZ0jHQb](url)

Thanks

**Comment by traud** [comment]
Thank you for the report and the specific log output.

Analysis: With Asterisk 13.7, those failing patches are not required anymore. Nowadays—thanks to the Asterisk team—the code of those four patches is part of Asterisk itself. Or stated differently: Since Asterisk 13.7, you have to apply just the two remaining patches `codec_amr.patch` and `build_tools.patch`.

Lesson learned: Next time, I am going to update the integrated patches here on GitHub already well before the release. Then, `patch` is able to detect the situation as a reversed patch, until I find the time to remove the patches from GitHub. So, thank you again for the report.

**Comment by kosfango** [comment]
Thank you for great job! I was very happy when saw yours repo.
